version: '3.8'
services:
  db:
    image: mariadb:11.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mentorship
      MYSQL_USER: mentorship
      MYSQL_PASSWORD: mentorshippass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    # volumes:
    #   - ./backend:/app

  frontend:
    environment:
      - HOST=0.0.0.0
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

volumes:
  db_data:
